# Generated by Django 4.2.5 on 2023-10-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='data',
            field=models.DateField(verbose_name='Дата записи клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.masters', verbose_name='Услуга клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='time',
            field=models.TimeField(verbose_name='Время записи клиента'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя мастера'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='masters',
            name='services',
            field=models.CharField(max_length=100, verbose_name='Услуга'),
        ),
    ]
